# Generated by Django 2.2.2 on 2020-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='funder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
