# Generated by Django 2.2.2 on 2020-12-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201207_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('can_validate_grant_application', 'Can validate grant application'), ('can_validate_fellowship', 'can Validate Fellowship'), ('can_view_contacts', 'Can view contacts'), ('can_edit_contacts', 'can edit contacts'), ('can_delete_contacts', 'can delete contacts'))},
        ),
    ]
