# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grant_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('call_id', models.CharField(max_length=100)),
                ('submission_deadline', models.DateField()),
                ('text', models.FileField(blank=True, null=True, upload_to='')),
                ('review_form', models.FileField(blank=True, null=True, upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('call_year', models.CharField(max_length=20)),
                ('generated_number', models.IntegerField(null=True)),
                ('scholarship_type', models.CharField(blank=True, choices=[('mastercard', 'Mastercard'), ('RI', 'Research and Innovation'), ('GTA', 'GTA')], max_length=32, null=True)),
            ],
            options={
                'ordering': ['submission_deadline'],
            },
        ),
        migrations.CreateModel(
            name='Commodityfocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.FileField(blank=True, null=True, upload_to='')),
                ('review_form', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='GrantCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('call_id', models.CharField(max_length=100)),
                ('submission_deadline', models.DateField()),
                ('text', models.FileField(blank=True, null=True, upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('call_year', models.CharField(max_length=20)),
                ('generated_number', models.IntegerField(null=True)),
                ('minimum_qualification', models.CharField(choices=[(None, '--please select--'), ('bac', 'BAC'), ('msc', 'MSC'), ('phd', 'PHD')], max_length=10, null=True)),
                ('commodity_focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calls.Commodityfocus')),
                ('grant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grant_types.Granttype')),
                ('proposal_sub_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calls.Subtheme')),
                ('proposal_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calls.Theme')),
            ],
            options={
                'ordering': ['-submission_deadline', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FellowshipCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('call_id', models.CharField(max_length=250)),
                ('submission_deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=250)),
                ('member_university', models.TextField()),
                ('home_institute_obligations', models.TextField()),
                ('host_institute', models.TextField()),
                ('goal', models.CharField(max_length=500)),
                ('objectives', models.TextField()),
                ('who_can_apply', models.TextField()),
                ('financial_support', models.TextField()),
                ('institute_obligations', models.TextField()),
                ('call_year', models.CharField(max_length=20)),
                ('generated_number', models.IntegerField(null=True)),
                ('fellowship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.FellowshipType')),
            ],
            options={
                'ordering': ['submission_deadline'],
            },
        ),
    ]
