# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('ruforum_grant_number', models.CharField(blank=True, max_length=100)),
                ('lead_institution', models.CharField(blank=True, max_length=200)),
                ('contact_person_from_lead_institution_if_not_RUFORUM', models.CharField(blank=True, max_length=200)),
                ('contact_person_at_ruforum', models.CharField(max_length=200)),
                ('partners', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('new_end_date', models.DateField(null=True)),
                ('project_status', models.CharField(choices=[(None, '---please select---'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], db_index=True, max_length=100)),
                ('project_duration', models.IntegerField(blank=True, help_text='enter the project duration in months')),
                ('donor_currency', models.CharField(blank=True, help_text='currency of the donor', max_length=100)),
                ('total_project_budget_original_currency', models.IntegerField(blank=True)),
                ('total_budget_us', models.IntegerField(blank=True)),
                ('total_budget_received_from_Donor_to_RUFORUM', models.IntegerField(blank=True)),
                ('ruforum_secretariat_staff_time', models.DateField(null=True)),
                ('annual_budget_available', models.IntegerField(blank=True)),
                ('project_goal', models.TextField(blank=True)),
                ('project_objectives', models.TextField(blank=True)),
                ('project_proposal', models.FileField(help_text='upload the full project proposal', null=True, upload_to='')),
                ('reporting_frequency', models.CharField(blank=True, help_text='monthly, quarterly, biannually, annually, etc', max_length=100)),
                ('ruforum_flagship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pme.Resultarea')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_objectives', models.TextField(blank=True)),
                ('broader_objectives_to_which_the_project_will_contribute', models.TextField(blank=True)),
                ('project_objectives', models.TextField(blank=True)),
                ('sources_of_information_to_indicators', models.TextField(blank=True)),
                ('specific_objective', models.TextField(blank=True)),
                ('indicators_that_clearly_show_that_objective_has_been_achieved', models.TextField(blank=True)),
                ('sources_of_information_that_exist_or_can_be_collected', models.TextField(blank=True)),
                ('necessary_factors_outside_the_beneficiaries_responsibility', models.TextField(blank=True)),
                ('expected_results', models.TextField(blank=True, help_text='what are the expected results, Detail them')),
                ('indicators_to_measure_expected_results', models.TextField(blank=True)),
                ('external_conditions_for_expected_results', models.TextField(blank=True)),
                ('key_activities', models.TextField(blank=True)),
                ('means_required_to_carry_out_activities', models.TextField(blank=True)),
                ('sources_of_information_about_action_progress', models.TextField(blank=True)),
                ('pre_conditions_required', models.TextField(blank=True)),
                ('conditions_outside_beneficiaries_control', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.ProjectManagement')),
            ],
        ),
    ]
