# Generated by Django 2.2.2 on 2020-12-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellowshipapplication',
            options={'permissions': (('assign_fellowship_validators', 'Can assign Fellowship Validators'), ('assign_fellowship_reviewers', 'Can assign Fellowship reviewers'))},
        ),
        migrations.RemoveField(
            model_name='fellowshipapplication',
            name='state',
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('noncompliant', 'Non Compliant'), ('rejected', 'Rejected'), ('selected_for_funding', 'Selected for Funding')], default='draft', max_length=20),
        ),
    ]
