# Generated by Django 2.2.2 on 2020-12-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship_applications', '0002_auto_20201210_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowshipapplication',
            old_name='status',
            new_name='state',
        ),
    ]
