# Generated by Django 2.2.2 on 2020-12-10 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fellowship_applications', '0004_auto_20201210_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipapplication',
            name='validators',
            field=models.ManyToManyField(blank=True, related_name='validator', to=settings.AUTH_USER_MODEL),
        ),
    ]
