# Generated by Django 2.2.2 on 2020-12-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship_applications', '0005_fellowshipapplication_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowshipappreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fellowship_applications.Fellowshipapplication'),
        ),
    ]
