# Generated by Django 2.2.2 on 2020-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship_applications', '0007_fellowshipapplication_fellowship_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellowshipapplication',
            options={'permissions': (('assign_fellowship_validators', 'Can assign Fellowship Validators'), ('assign_fellowship_reviewers', 'Can assign Fellowship reviewers'), ('can_validate_fellowship_app', 'Can Validate Fellowship Application'))},
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='compliance_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='validated_cv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='validated_home_institute',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='validated_host_institute',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellowshipapplication',
            name='validated_letter_of_release',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
