# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('field_name', models.TextField()),
                ('label', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='file_templates')),
            ],
        ),
    ]
