# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='To be computed from Start and End Date')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=30)),
                ('fellowship_id', models.CharField(blank=True, max_length=30, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fellowship_approvals', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(blank=True, help_text='Principal Investigator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fellowships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipStudentmembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fellowship.Fellowship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'fellowship')},
            },
        ),
        migrations.CreateModel(
            name='FellowshipComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fellowship_comments', to=settings.AUTH_USER_MODEL)),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fellowship_comments', to='fellowship.Fellowship')),
            ],
        ),
        migrations.AddField(
            model_name='fellowship',
            name='students',
            field=models.ManyToManyField(blank=True, through='fellowship.FellowshipStudentmembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
