# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('grants_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('theme', models.TextField(blank=True, null=True)),
                ('value_chain', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='To be computed from Start and End Date')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=30)),
                ('grant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('project_objectives', models.TextField()),
                ('collaborators', models.TextField()),
                ('grant_year', models.CharField(max_length=20)),
                ('generated_number', models.IntegerField(default=1, null=True)),
                ('has_reports', models.BooleanField()),
                ('reporting_period', models.PositiveIntegerField(blank=True, choices=[(None, '--please select'), (3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (15, '15 Months'), (18, '18 Months'), (21, '21 Months')], null=True)),
                ('report_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('grant_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_applications.Grantapplication')),
                ('pi', models.ForeignKey(blank=True, help_text='Principal Investigator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh')], default='first', max_length=20)),
                ('Support_type', models.CharField(choices=[('research_only', 'Research only'), ('research_and_tuition', 'Research and Tuition'), ('tution_only', 'Tuition only')], default='research_and_tuition', max_length=20)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.Grant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Student')),
            ],
            options={
                'unique_together': {('student', 'grant')},
            },
        ),
        migrations.CreateModel(
            name='GrantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grant_comments', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_comments', to='grants.Grant')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='students',
            field=models.ManyToManyField(blank=True, through='grants.Studentmembership', to='contacts.Student'),
        ),
    ]
