# Generated by Django 2.2.2 on 2020-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='count_holidays',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='hr_comment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='human_resource_comment',
            field=models.TextField(null=True),
        ),
    ]
