# Generated by Django 2.2.2 on 2020-12-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20201203_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='spouse',
            new_name='name_of_spouse',
        ),
    ]
