# Generated by Django 2.2.2 on 2020-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20201204_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approval',
            field=models.CharField(blank=True, choices=[(None, '--please select--'), ('pending', 'Pending Approval'), ('approved', 'Leave Approved'), ('not_approved', 'Not Approved')], default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='remarks',
            field=models.TextField(null=True, verbose_name='Remarks/Reasons by the Applicant (Applies to Only Compassionate & Study Leave)'),
        ),
    ]
