# Generated by Django 2.2.2 on 2020-12-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20201204_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_application',
        ),
    ]
