# Generated by Django 2.2.2 on 2020-12-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_remove_leave_leave_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.LeaveApplication'),
        ),
    ]
