# Generated by Django 2.2.2 on 2020-12-06 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0006_leave_leave_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='human_resource_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_human_hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
