# Generated by Django 2.2.2 on 2020-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_leaveapplication_human_resource_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'permissions': (('comment_on_leave', 'Can Comment on Leave Applications'),)},
        ),
    ]
