# Generated by Django 2.2.2 on 2020-12-08 00:42

from django.db import migrations,models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_auto_20201206_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'permissions': (('comment_on_leave', 'Can Comment on Leave Applications'), ('recommend_on_leave', 'Can Recommend on Leave Applications'), ('can_approve_leave', 'Can Approve Leave Applications'))},
        ),
        
    ]
