# Generated by Django 2.2.2 on 2020-12-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_auto_20201208_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_comment',
            field=models.TextField(null=True),
        ),
    ]
