# Generated by Django 2.2.2 on 2020-12-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_auto_20201208_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.LeaveApplication'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_days',
            field=models.PositiveIntegerField(null=True, verbose_name='Leave Days Approved'),
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=300)),
                ('achievement', models.DateField(blank=True, null=True)),
                ('supervisor_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraisal',
            options={'permissions': (('review_staff_appraisals', 'can review staff appraisals'),)},
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='date_employee_begun_present_position',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='date_of_last_appraisal_review',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='date_of_this_appraisal_review',
            field=models.DateField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='leadership_competency',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='leadership_competency',
            field=models.ForeignKey(help_text='Tick one leadership competence', null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.LeadershipCompetency'),
        ),
    ]
