# Generated by Django 2.2.2 on 2020-12-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_auto_20201210_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month6Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job_title', models.CharField(max_length=50, null=True)),
                ('implementation_activites', models.TextField(blank=True, null=True)),
                ('implementation_activites2', models.TextField(blank=True, null=True)),
                ('planned_activities', models.TextField(blank=True, null=True)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('staff_comment', models.TextField(blank=True, null=True)),
                ('deputy_executive_comment', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month6appraisal_staff', to='hrm.StaffProfile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month6appraisal_supervisor', to='hrm.StaffProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Month6PlannedAppraisalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.Month6Appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='Month6AppraisalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('achievement', models.TextField()),
                ('staff_remarks', models.TextField()),
                ('supervisor_remarks', models.TextField()),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.Month6Appraisal')),
            ],
        ),
    ]
