# Generated by Django 2.2.2 on 2020-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_month6appraisal_month6appraisalactivity_month6plannedappraisalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='month6appraisal',
            name='submission_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='month6appraisal',
            name='implementation_activites',
            field=models.TextField(blank=True, null=True, verbose_name='Implemented activities'),
        ),
        migrations.AlterField(
            model_name='month6appraisal',
            name='implementation_activites2',
            field=models.TextField(blank=True, null=True, verbose_name='Lessons from implementation'),
        ),
        migrations.AlterField(
            model_name='month6appraisalactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='month6appraisalactivity',
            name='supervisor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
