# Generated by Django 2.2.2 on 2020-12-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firststudentreport',
            name='tuition_paid',
            field=models.IntegerField(blank=True, choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
    ]
