# Generated by Django 2.2.2 on 2020-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_reports', '0005_auto_20201209_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laststudentreport',
            name='student_graduated',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth102report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='research_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth108report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth12report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth18report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth24report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='research_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth30report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='defended_proposal_delay_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='research_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth36report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth42report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth48report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth54report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth54report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth54report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth54report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='research_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth60report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth66report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth72report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth78report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth84report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth90report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='defended_proposal',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='done_academic_requirements',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='passed_second_courses',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='progress_as_planned',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='thesis_defense',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='thesis_submission',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='studentmonth96report',
            name='thesis_submission_external',
            field=models.IntegerField(choices=[(None, '--please select--'), (2, 'Yes'), (3, 'No')], null=True),
        ),
    ]
