# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[(None, '--please select--'), ('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50, verbose_name='status')),
                ('priority', models.CharField(choices=[(None, '--please select--'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, verbose_name='priority')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('new_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(related_name='users_tasks', to='hrm.StaffProfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
