# Generated by Django 2.2.2 on 2020-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('noncompliant', 'Non Compliant'), ('rejected', 'Rejected'), ('selected_for_funding', 'Selected for Funding')], default='draft', max_length=20, null=True),
        ),
    ]
