# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruforumcomment',
            fields=[
                ('comment_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('comment_type', models.CharField(blank=True, choices=[('general', 'General'), ('administrative', 'Administrative'), ('technical', 'Technical')], max_length=32, null=True)),
            ],
        ),
    ]
