# Generated by Django 2.2.2 on 2020-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attendance', models.FileField(blank=True, help_text='Attach attendance list in excell format, if any.', null=True, upload_to='')),
                ('event_description', models.TextField()),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_four', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_five', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
